/**
 * DOM Builder Mixin
 * Handles DOM creation, manipulation, and event handling
 */

import {
  DEFAULT_LINE_STROKE_WIDTH,
  LINE_OPACITY_INACTIVE,
  LINE_OPACITY_ACTIVE,
  NEARLY_HORIZONTAL_THRESHOLD,
  FULL_CIRCLE_DEGREES,
} from './constants.js';

export const DOMBuilder = {
  /**
   * Triggers haptic feedback on mobile devices
   * Uses the component's configured settings (hapticFeedbackEnabled and hapticFeedbackDuration)
   */
  triggerHapticFeedback() {
    if (!this.hapticFeedbackEnabled) {
      return;
    }
    if (navigator.vibrate && typeof navigator.vibrate === 'function') {
      try {
        navigator.vibrate(this.hapticFeedbackDuration);
      } catch (e) {
        // Silently fail if vibration is not supported or blocked
      }
    }
  },

  buildDOM() {
    this.innerHTML = `
			<div class="selector">
				<div class="label-column left" id="leftColumn">
					<!-- Left labels will be generated by JavaScript -->
				</div>

				<div class="knob-wrap">
					<svg id="lineContainer" width="100%" height="100%" style="position: absolute; overflow: visible;">
						<!-- Lines will be generated by JavaScript -->
					</svg>
					<div class="knob" tabindex="0" role="listbox" aria-label="Theme selector" id="dialKnob">
						<div class="indicator"></div>
						<div class="advance" id="advanceButton" aria-label="Switch to next option"></div>
					</div>
				</div>

				<div class="label-column right" id="rightColumn">
					<!-- Right labels will be generated by JavaScript -->
				</div>
			</div>
		`;
  },

  createLabelsAndLines() {
    const leftColumn = this.querySelector('#leftColumn');
    const rightColumn = this.querySelector('#rightColumn');
    const lineContainer = this.querySelector('#lineContainer');
    const advanceButton = this.querySelector('#advanceButton');
    const dialKnob = this.querySelector('#dialKnob');

    if (leftColumn) leftColumn.innerHTML = '';
    if (rightColumn) rightColumn.innerHTML = '';
    if (lineContainer) lineContainer.innerHTML = '';
    this.hitAreas = [];

    this.OPTIONS.forEach((option, index) => {
      const isLeft = index < this.leftCount;
      const container = isLeft ? leftColumn : rightColumn;
      let angleIndex;
      if (isLeft) {
        angleIndex = this.rightCount + index;
      } else {
        angleIndex = index - this.leftCount;
      }
      const angle = this.spokeAngles[angleIndex];
      const angleRad = (angle * Math.PI) / 180;

      const columnCenter = this.labelColumnHeight / 2;
      const verticalOffset = Math.sin(angleRad) * this.labelVerticalOffsetScale;
      const topPosition = columnCenter + verticalOffset;

      const label = document.createElement('label');
      label.className = 'dial-label';
      const span = document.createElement('span');
      span.textContent = option;
      label.appendChild(span);
      label.dataset.index = index;
      label.dataset.angle = angle;

      label.style.top = `${topPosition}px`;
      if (isLeft) {
        label.style.right = '0';
      } else {
        label.style.left = '0';
      }

      label.addEventListener('click', () => {
        this.triggerHapticFeedback();
        this.currentIndex = index;
        this.updateSelector();
      });

      if (container) container.appendChild(label);
      this.labels.push(label);

      const hitArea = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
      hitArea.setAttribute('class', 'spoke-line-hit-area');
      hitArea.setAttribute('fill', 'none');
      hitArea.setAttribute('stroke', 'transparent');
      hitArea.setAttribute('stroke-width', this.hitAreaStrokeWidth.toString());
      hitArea.setAttribute('stroke-linejoin', 'miter');
      hitArea.setAttribute('pointer-events', 'auto');
      hitArea.dataset.index = index;
      hitArea.setAttribute('points', '');

      hitArea.addEventListener('click', () => {
        this.triggerHapticFeedback();
        this.currentIndex = index;
        this.updateSelector();
      });

      const line = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
      line.setAttribute('class', 'spoke-line');
      line.setAttribute('fill', 'none');
      line.setAttribute('stroke', 'var(--ds-color-ink)');
      // Note: Using internal --ds-internal-* variables which feed into public --ds-line-* variables in CSS
      line.setAttribute('stroke-width', `var(--ds-internal-line-stroke-width, ${DEFAULT_LINE_STROKE_WIDTH})`);
      line.setAttribute('opacity', `var(--ds-internal-line-opacity-inactive, ${LINE_OPACITY_INACTIVE})`);
      line.setAttribute('stroke-linejoin', 'miter');
      line.setAttribute('pointer-events', 'none');
      line.dataset.index = index;

      lineContainer.appendChild(hitArea);
      lineContainer.appendChild(line);
      this.lines.push(line);
      this.hitAreas.push(hitArea);
    });

    if (advanceButton) {
      advanceButton.addEventListener('click', () => {
        this.triggerHapticFeedback();
        this.currentIndex = (this.currentIndex + 1) % this.OPTIONS.length;
        this.updateSelector();
      });
    }

    // Add keyboard navigation to the knob
    if (dialKnob) {
      dialKnob.addEventListener('keydown', (e) => {
        switch (e.key) {
          case 'ArrowRight':
          case 'ArrowDown':
            e.preventDefault();
            this.triggerHapticFeedback();
            this.currentIndex = (this.currentIndex + 1) % this.OPTIONS.length;
            this.updateSelector();
            break;
          case 'ArrowLeft':
          case 'ArrowUp':
            e.preventDefault();
            this.triggerHapticFeedback();
            this.currentIndex = (this.currentIndex - 1 + this.OPTIONS.length) % this.OPTIONS.length;
            this.updateSelector();
            break;
          case 'Home':
            e.preventDefault();
            this.triggerHapticFeedback();
            this.currentIndex = 0;
            this.updateSelector();
            break;
          case 'End':
            e.preventDefault();
            this.triggerHapticFeedback();
            this.currentIndex = this.OPTIONS.length - 1;
            this.updateSelector();
            break;
          case ' ':
          case 'Enter':
            e.preventDefault();
            this.triggerHapticFeedback();
            // For space/enter, advance to next option
            this.currentIndex = (this.currentIndex + 1) % this.OPTIONS.length;
            this.updateSelector();
            break;
          default:
            break;
        }
      });
    }

    // Add haptic feedback for rotation completion
    const indicator = this.querySelector('.indicator');
    if (indicator) {
      indicator.addEventListener('transitionend', (e) => {
        // Only trigger for transform transitions (the rotation)
        if (e.propertyName === 'transform' && this.isInitialized && this.hapticFeedbackEnabled) {
          // Lighter vibration for completion (15ms)
          if (navigator.vibrate && typeof navigator.vibrate === 'function') {
            try {
              navigator.vibrate(15);
            } catch (err) {
              // Silently fail
            }
          }
        }
      });
    }
  },

  updateLines() {
    const knobWrap = this.querySelector('.knob-wrap');
    if (!knobWrap) return;

    const centerX = this.knobCenter;
    const centerY = this.knobCenter;

    const tempDiv = document.createElement('div');
    tempDiv.style.cssText = `
      position: absolute;
      visibility: hidden;
      width: var(--ds-radius-outer);
      height: var(--ds-horizontal-line-length);
      max-width: var(--ds-max-line-length);
      max-height: var(--ds-horizontal-line-end-offset);
    `;
    this.appendChild(tempDiv);
    const tempStyle = getComputedStyle(tempDiv);

    const knobRadius = parseFloat(tempStyle.width) || 90;
    const horizontalLength = parseFloat(tempStyle.height) || 100;
    const maxSpokeLengthValue = parseFloat(tempStyle.maxWidth) || 80;
    const horizontalLineEndOffsetValue = parseFloat(tempStyle.maxHeight) || 10;

    this.removeChild(tempDiv);

    void getComputedStyle(knobWrap).width;
    if (this.labels.length > 0) {
      void getComputedStyle(this.labels[0]).top;
    }

    this.labels.forEach((label, index) => {
      const labelRect = label.getBoundingClientRect();
      const knobWrapRect = knobWrap.getBoundingClientRect();

      const angle = parseFloat(label.dataset.angle);
      const angleRad = (angle * Math.PI) / 180;
      const isLeft = index < this.leftCount;

      const labelX = isLeft ? labelRect.right - knobWrapRect.left : labelRect.left - knobWrapRect.left;
      const labelY = labelRect.top + labelRect.height / 2 - knobWrapRect.top;

      const spokeStartX = centerX + Math.cos(angleRad) * knobRadius;
      const spokeStartY = centerY + Math.sin(angleRad) * knobRadius;

      const maxSpokeLength = maxSpokeLengthValue;

      let intersectX, intersectY;

      if (Math.abs(Math.sin(angleRad)) < NEARLY_HORIZONTAL_THRESHOLD) {
        intersectX = spokeStartX;
        intersectY = labelY;
      } else {
        const t = (labelY - spokeStartY) / Math.sin(angleRad);
        const spokeLength = Math.abs(t);
        if (spokeLength > maxSpokeLength) {
          const limitedT = t > 0 ? maxSpokeLength : -maxSpokeLength;
          intersectX = spokeStartX + limitedT * Math.cos(angleRad);
          intersectY = labelY;
        } else {
          intersectX = spokeStartX + t * Math.cos(angleRad);
          intersectY = labelY;
        }
      }

      const horizontalEndX = isLeft
        ? Math.min(intersectX - horizontalLineEndOffsetValue, labelX + horizontalLength)
        : Math.max(intersectX + horizontalLineEndOffsetValue, labelX - horizontalLength);
      const horizontalEndY = labelY;

      const points = `${labelX},${labelY} ${horizontalEndX},${horizontalEndY} ${intersectX},${intersectY} ${spokeStartX},${spokeStartY}`;
      this.lines[index].setAttribute('points', points);

      if (this.hitAreas[index]) {
        this.hitAreas[index].setAttribute('points', points);
      }
    });
  },

  updateSelector() {
    if (this.labels.length === 0) return;

    const targetAngle = parseFloat(this.labels[this.currentIndex].dataset.angle);

    if (!this.isInitialized) {
      this.currentAngle = targetAngle;
      this.isInitialized = true;
      this.previousIndex = this.currentIndex;
    } else {
      let delta = targetAngle - this.currentAngle;

      while (delta > 180) delta -= FULL_CIRCLE_DEGREES;
      while (delta < -180) delta += FULL_CIRCLE_DEGREES;

      if (Math.abs(delta) === 180) {
        if (this.currentIndex > this.previousIndex) {
          delta = 180;
        } else {
          delta = -180;
        }
      }

      this.currentAngle = this.currentAngle + delta;
    }

    this.style.setProperty('--ds-indicator-angle', `${this.currentAngle}deg`);

    // Update the knob's aria-label to reflect current selection
    const dialKnob = this.querySelector('#dialKnob');
    if (dialKnob) {
      dialKnob.setAttribute('aria-label', `Theme selector: ${this.OPTIONS[this.currentIndex]} selected`);
    }

    this.labels.forEach((label, index) => {
      const line = this.lines[index];
      if (index === this.currentIndex) {
        label.classList.add('active');
        line.classList.add('active');
        // Note: Using internal --ds-internal-line-opacity-* variables (feed into public --ds-line-opacity-* in CSS)
        line.setAttribute('opacity', `var(--ds-internal-line-opacity-active, ${LINE_OPACITY_ACTIVE})`);
        line.setAttribute('stroke', 'var(--ds-color-selection)');
      } else {
        label.classList.remove('active');
        line.classList.remove('active');
        line.setAttribute('opacity', `var(--ds-internal-line-opacity-inactive, ${LINE_OPACITY_INACTIVE})`);
        line.setAttribute('stroke', 'var(--ds-color-ink)');
      }
    });

    if (this.previousIndex !== this.currentIndex && this.isInitialized) {
      this.dispatchChangeEvent();
      this.previousIndex = this.currentIndex;
    }
  },

  dispatchChangeEvent() {
    const event = new CustomEvent('change', {
      bubbles: true,
      cancelable: true,
      detail: {
        value: this.OPTIONS[this.currentIndex],
        index: this.currentIndex,
        previousValue: this.OPTIONS[this.previousIndex],
        previousIndex: this.previousIndex,
      },
    });

    const onchangeAttr = this.getAttribute('onchange');
    const originalOnchange = this.onchange;

    if (onchangeAttr) {
      this.removeAttribute('onchange');
      delete this.onchange;
    }

    this.dispatchEvent(event);

    if (onchangeAttr) {
      try {
        const handler = new Function('event', onchangeAttr);
        handler.call(this, event);
      } catch (e) {
        console.warn('Error executing onchange handler:', e);
      }
      this.setAttribute('onchange', onchangeAttr);
    } else if (typeof originalOnchange === 'function') {
      originalOnchange.call(this, event);
    }
  },
};
